require('dotenv/config')
const { PrismaClient } = require('../src/generated/prisma')
const { PrismaPg } = require('@prisma/adapter-pg')

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

const entries = [
  // ── FOLK SONGS ────────────────────────────────────────────────────────────
  { title: "Ka nilugdang iyan on usab paibabow", manoboTitle: "Ka nilugdang iyan on usab paibabow", englishTitle: "What Was Buried Has Surfaced Again", type: "FOLK_SONG", content: "The song captures the journey of the Manobo tribe, who have long felt invisible and neglected, burdened by a heavy sense of abandonment. It tells the story of our struggle to maintain our identity without the support we need, highlighting moments when our voices went unheard as they sought recognition. Despite the challenges we faced when presenting our resolutions, we remained determined and resilient.", transcription: "Lantawod diya lawod nig duma kan bayod soe tribu ko no daog-daog mahawig no katuigan, niglubong on tu kamingaw kunag pakabarog so wara ka silungan musombong sa kagamhanan Kuna intawon ug paminugon pasahan to resolution kandan gayod pag palisudlisuron Kuna nog paluapon kandan pagyud palugoylugoyuntribu mapailubon paubus nalang intawon uhaw tu pag mahal kuwang tu pag pangga uhaw tu pagtabang tu katribuhan wara lamang dahuma tu mgo katuigan presidente Ramos ka Ipra Law kandin pig amidahan tuig 1997 Gloria Arroyo kandin Tig segundahan buyan tu of October 29. Kandin soe Tig permahan.  Tig maduan tu INCP tu Ipra Law panalipdan 8371 kinahanglan dudusunan Aron matabangan mga katribuhan Kay duon tu kalisdanan lantawa ka duma now tu kabus tu pag aha- aha Kun wuhig pad lamang malubog matin ow wara lamang dahuma nu mgo katuigan kan pig lugdang nu wohig iyan op isab ug pa ibabow.", translation: "What Was Buried Has Surfaced Again", audioFile: "/audio/nilugdang.mp3", audioDuration: 25, source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Sitio Dam, Brgy. Tudela", province: "Agusan del Sur", municipality: "Trento", barangay: "Tudela", genre: "SONG", themes: '["NATURE_AND_ENVIRONMENT","HEROIC_DEEDS"]', culturalElements: '["Tribal Recognition","Cultural Identity","Resilience","Manobo Folk Song"]' },
  { title: "Kapoit to Kanak Kahimtang", manoboTitle: "Kapoit to Kanak Kahimtang", englishTitle: "The Hardship of My Situation", type: "FOLK_SONG", content: "The song conveys a profound sense of emotional struggle, loneliness, and longing. The mountains symbolize the burdens and hardships faced by the narrator, reinforcing their feelings of being trapped in a difficult situation. The memory of their mother introduces a theme of loss and sorrow, suggesting that the narrator finds both comfort and pain in remembering her. Additionally, the mention of hurtful neighbors highlights social isolation, emphasizing the emotional distance between the narrator and their community. Through these elements, the song reflects the internal conflict of the narrator, showcasing how personal grief and external struggles intertwine to deepen their sense of despair.", transcription: "Kapait soe Kanak kahimtang bubungan SI Kanak pig ugpaan ug sinugow a Man usahay tug paka dumdum a tu kanay inoy, labi on tu mgo silingan Kay Kandan amana tamayan sinugow a tug kadumduman tu kandan pagtamay.Oh a dios on lang iyo tibu Kay kani a man tu tikang, ug Tambo duon tu bintana Dahun tu misitas na Puno on tu mgo luha. Dini ad kuntoon lungod pigsungod Tu ma aslag nu bayod sinugow a man usahay tug kadumdum a tu iyo pag tamay ug sinugow a man usahay tug ka dumduman a tu kanay inoy.", translation: "How hardship my situation is, For the mountains are my home. I weep when I remember my mother. But, because of these neighbors, For they have scorned me. I sometimes cry when I recall your disdain. Oh, farewell to all of you, For I am about to leave. I will look out the window, Leaves of the misitas, Full of tears. Here I am, far away, Facing the great waves. I sometimes cry when I remember your disdain. I sometimes cry when I think of my mother.", audioFile: "/audio/kapoit.mp3", audioDuration: 20, source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Sta Maria", province: "Agusan del Sur", municipality: "Trento", barangay: "Sta Maria", genre: "SONG", themes: '["SOCIAL_CUSTOMS","DEATH_AND_AFTERLIFE"]', culturalElements: '["Family Life","Social Isolation","Grief and Loss","Manobo Folk Song"]' },
  { title: "Kasaysayan tu Katribuhan", manoboTitle: "Kasaysayan tu Katribuhan", englishTitle: "History of the Tribe", type: "FOLK_SONG", content: "The song explores poignant themes of loss, resilience, and the enduring connection between the tribe and their land. By recounting the historical plight of the tribe during the 18th century, the writer highlights the detrimental impact of colonialism and exploitation by foreign powers. The emphasis on the indoctrination by the Spaniards serves to illustrate how cultural identity and ancestral knowledge were undermined, leading to a disconnection from the mountains that were once their lifeblood.", transcription: "Iyan soe tu kasaysayan tu kahimtang tu katribuhan 18 century Pig duktrinahan tu spanyol soe kaotawan kinahanglan iyo ampingan Soe iyo kabubunganan Kay iya soe ka iyo nog kabuhian. Laboy tu katuigan pilipinas pig hawakan tu gobyerno nu gamhanan  Apil ka katribuhan kandan pig tagunan apil ka kabubunganan kandan Tig hawakan dini pilipinas Tig palasakan tu stranghero nu sapian Pig parentahan tu gobyerno SI eta kabungbunganan nu wara bisan sibuok Nu katribuhan pig panumanghiran pig hakot tu stranghero nu sapian soe eta kayamanan dapas su kan bulawan, pasak dow kabatuhan nabawi tu katribuhan soe upaw on nu kabungbunganan nagastuhan tu katribuhan mahawig nu katuigan kandan pig atubang.  Ug amono on lamang soe sumusunod nu kaliwatan nu nigkawara on soe eta kayamanan no nig kawara on soe eta kayamanan.", translation: "This is the history of the tribe's situation in the 18th century. The Spaniards indoctrinated the people, emphasizing the need to care for their mountains as their source of livelihood. Over the years, the Philippines was governed by powerful authorities, including the tribes and their lands. The country was opened to wealthy foreigners, and the government leased the mountains without the knowledge of even a single member of the tribe. These affluent foreigners exploited the tribe's resources, extracting gold, land, and stones. The tribe reclaimed the now barren mountains, enduring long years of hardship. What will become of the future generations now that our wealth has vanished?", audioFile: "/audio/kasaysayan.mp3", audioDuration: 28, source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Sta Maria", province: "Agusan del Sur", municipality: "Trento", barangay: "Sta Maria", genre: "SONG", themes: '["HISTORICAL_EVENTS","HEROIC_DEEDS","SOCIAL_CUSTOMS"]', culturalElements: '["Historical Struggle","Colonialism","Cultural Identity","Tribal Resilience","Manobo Folk Song"]' },
  { title: "Opaw on tu Kabubunganan", manoboTitle: "Opaw on tu Kabubunganan", englishTitle: "The Mountains Are Bare", type: "FOLK_SONG", content: "The song sends a strong message about the harm done to our environment and the need for everyone to take action. The song talks about how companies have ruined the beautiful mountains and forests, which used to be full of life. This loss highlights how important it is to protect nature for future generations. By asking what will happen to the next generation when the land’s resources are gone, the song makes us think about the long-term effects of ignoring our environment. It suggests that future generations might only hear stories about the rich nature that once existed instead of experiencing it firsthand.", transcription: "Mga kadumahan dasigon ko iyu pananom kinow Tu kayo Kay naupow on tu mgo bubungan ta Tig ubos On ma tu kumpaniya ita nuon una ug ahaon nu madiyoway Ka hitsura, pero kuntuon warad nada Kay tiwasan on Man tu mgo dayuhan. Ug amo on man SI ita kabataan nu warad bahandi di ita Kapasakan bisan Gani bulawan kunad Dan katilawan To kandan kadinogan sigulanon da'an Soe bubungan ta uranon ug siguyon su wad kakayuhan ug Pakasagang na ngo angas on soe kapangpangan. Tu mgo sapa tibu nangatambakan nangkatabunan on man Tu mgo batang mga isda warad on man kaugpaan Iyan soe ka hinungdan no warad ita kapanglayahan Kay Warad on man mga kaugpaan.", translation: "My fellowmen, I encourage you to plant trees because our mountains have become barren. These forests have been destroyed by companies. In the past, our mountains were beautiful to look at, but now they are ruined because they have been exploited by outsiders. What will happen to the next generation when the land's riches are gone? Even gold will no longer be something they can experience—only stories will remain. These mountains, once lush, are now battered by rain and floods because there are no more trees to hold the soil.  The rivers have been buried, their banks eroded, and the fish have disappeared. This is why we can no longer fish—there are no more places for them to live.", audioFile: "/audio/opaw.mp3", audioDuration: 18, source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Sta Maria", province: "Agusan del Sur", municipality: "Trento", barangay: "Sta Maria", genre: "SONG", themes: '["NATURE_AND_ENVIRONMENT","SOCIAL_CUSTOMS"]', culturalElements: '["Environmental Destruction","Deforestation","Future Generations","Call to Action","Manobo Folk Song"]' },
  { title: "Kadikiluman", manoboTitle: "Kadikiluman", englishTitle: "The Night Has Come", type: "FOLK_SONG", content: "The song portrays deep sorrow and longing as the speaker faces the departure of a loved one. The arrival of night symbolizes sadness, with heavy emotions expressed through tears and imagery of soaked leaves. The contrast of singing birds against the speaker's loneliness emphasizes their heartache while waiting for the loved one's return. Overall, the song captures the profound pain of loss and the desire for reconnection.", transcription: "Kan adlaw madani ug sayop Nu sikuna mig padiyo-un gadud Mig abot tu kakuba tu daegeha Mga yuha migtagdo tu mata Madani-un ug kadukilom Kan mga dahon nabasa un-tu Gabon Mga mata ko angud tu tabukan mga yuha wada pag undang Mig abot kan kadukiluman mig tahon sikan manok - manok Nang batog ang mga kalanggaman Mig tagad a TU pag balik now Wada kaman ug dajon abot Mig Pauli ka dinit bayoy ta Sinugawang tu kahadlok ko agon ug katagaka nayagak tu kasakit ko Mig tag- enop ad pagkadukilom kanay kasakit Nahingpit gadud yabion tu sikiyo nu Pag pa now Dow dada angud tu bayod Mig dugang kan kamingaw uto Nasakit at sikiyo nu pagpanow Natingay- a kan gugma ko iyo diya yain pig buguy nu Mig dangat kan kadukilom Mig duma isab ka kamingaw Yabi-on mapaminog nu tu kan huni tu nga kayow Pag simag diya tu silatan Pag yugwa tu kan aedow Pagyajang tu mgo mamang pig domdom ko ikow.", translation: "The night has come, you're about to leave And you're really far away now The heaviness in my chest has arrived Tears are falling from my eyes Night is near The leaves are soaked and wet My eyes are like they are bleeding, the tears never stop The night has come The birds are singing I wait for your return But you never came Will you come back to our home So that my fears will disappear And you'll know that my pain is gone I dream at night My pain is truly deep, especially because of your departure It feels like it's carried away, like waves My loneliness grows as my pain deepens With your departure, I'm confused was my love for you Given to someone else, somewhere far away? Night has arrived and so has the loneliness It's harder now, especially when I hear the sounds of the birds, I remember you when the sun rises as the animals walk away, I remember you.", audioFile: "/audio/kadikiluman.mp3", audioDuration: 22, source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Sta Maria", province: "Agusan del Sur", municipality: "Trento", barangay: "Sta Maria", genre: "SONG", themes: '["COURTSHIP_AND_MARRIAGE","DEATH_AND_AFTERLIFE"]', culturalElements: '["Love and Longing","Night Symbolism","Separation and Loss","Manobo Folk Song"]' },
  // ── PROVERBS (Panultihon) ─────────────────────────────────────────────────
  { title: "Panultihon (Life is hard)", manoboTitle: "Panultihon", englishTitle: "Life is hard", type: "ORAL_LITERATURE", content: "This proverb emphasizes integrity and resisting temptation. Even in difficult times, upholding your values is prioritized over compromising them for personal gain. It suggests true happiness stems from principled living, regardless of hardship.", transcription: "inggad nukoy ka lisud kan kinabuhi, mas marujow pad nug antus ki to ka buntas kaysa ug himo tu saya nu Kuna ko kinahangyan dawatun", translation: "No matter how hard life is, it's better to suffer from hunger than to do things you shouldn't.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "PROVERB", themes: '["MORAL_LESSONS","HEROIC_DEEDS"]', culturalElements: '["2nd POV","Courage and Resilience","Manobo Proverb"]' },
  { title: "Panultihon (Trust slowly)", manoboTitle: "Panultihon", englishTitle: "Trust slowly", type: "ORAL_LITERATURE", content: "This proverb highlights the delicate and time-consuming nature of building trust. Rushing trust can lead to disappointment; consistent effort is key.", transcription: "salig kilang permi su inggad hinuy hinuy, ugka abut tada inggad maintok", translation: "Trust is always slow, you can only achieve small things.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "PROVERB", themes: '["MORAL_LESSONS","SOCIAL_CUSTOMS"]', culturalElements: '["2nd POV","Conflict and Resolution","Manobo Proverb"]' },
  { title: "Panultihon (Peace and cure loneliness)", manoboTitle: "Panultihon", englishTitle: "Peace and cure loneliness", type: "ORAL_LITERATURE", content: "The proverb emphasizes the power of listening in fostering peace and connection. Active listening promotes empathy and reduces feelings of isolation.", transcription: "paminug, su sie maka daya ita tu kalinuw tambi tu kamingow", translation: "Listen, because it can bring peace and cure loneliness.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "PROVERB", themes: '["COURTSHIP_AND_MARRIAGE","SOCIAL_CUSTOMS"]', culturalElements: '["2nd POV","Love and Relationship","Manobo Proverb"]' },
  { title: "Panultihon (Change your life)", manoboTitle: "Panultihon", englishTitle: "Change your life", type: "ORAL_LITERATURE", content: "This proverb is metaphorical. It suggests that self-abuse or allowing mistreatment hinders progress. Self-respect and setting boundaries are crucial for personal growth.", transcription: "malisud ug yangoy, tu ikuw mismo sigeg abusar", translation: "It's hard to swim if you keep abusing yourself.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "PROVERB", themes: '["COURTSHIP_AND_MARRIAGE","MORAL_LESSONS"]', culturalElements: '["2nd POV","Love and Relationship","Manobo Proverb"]' },
  { title: "Panultihon (Attitude matters most)", manoboTitle: "Panultihon", englishTitle: "Attitude matters most", type: "ORAL_LITERATURE", content: "This proverb stresses the importance of inner beauty over outward appearances. True worth comes from character and actions, not superficial qualities. It encourages judging people based on their heart and behavior.", transcription: "Marujow dag ahaun kan bayho nu, Piro kan kinaiya nu kunag ka kuun", translation: "Your face is beautiful, but your behavior is not edible.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "PROVERB", themes: '["SOCIAL_CUSTOMS","MORAL_LESSONS"]', culturalElements: '["2nd POV","Social Justice and Inequality","Manobo Proverb"]' },
  // ── FOLKTALES ─────────────────────────────────────────────────────────────
  { title: "Kan isda diya tu sapa (The Fish in the Stream)", manoboTitle: "Kan isda diya tu sapa", englishTitle: "The Fish in the Stream", type: "ORAL_LITERATURE", content: "A fish learns that the stream's water is a shared resource, benefiting not just its family but all creatures.", transcription: "Sa bukano idow ,na madigos kan isda diya tu sapa ,wada kandin ka taga no kan doma no hayop nig inom diya tu wohig diya tu sapa,na ngosip kandin tokan sabuka no hayop \"madudiman diay kan og katabangan tukan no sapa kuna lang no kanami ?pangosip to isda.nig tubag kan kabayu \"gusto koy isab tukan wohig,para konakoy og uhawon para maka podot koy tu kusog Naka sabot kan isda tukan wohig no pig gamitdin kuna lang no para to pamilya din ,pang tibu Diay tukan namogo", translation: "one day, the fish was bathing in the stream, he didn't know that other animals were drinking water from the stream, he asked an animal \"the stream can help many people, not just us?\" ask the fish. The horse replied, \"We need water, so we don't get thirsty and get energy.\" The fish realized that the water he was using was not only for his family, but for all those in need.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "FOLKTALE", themes: '["SOCIAL_CUSTOMS","NATURE_AND_ENVIRONMENT","MORAL_LESSONS"]', culturalElements: '["2nd POV","Animal VS Nature","Conflict and Resolution","Resource Sharing","Social Justice"]' },
  { title: "Diwata duun tu wuhig (The Fairy of the Stream)", manoboTitle: "Diwata duun tu wuhig", englishTitle: "The Fairy of the Stream", type: "ORAL_LITERATURE", content: "Tala, the river goddess, rewards those who care for the stream, emphasizing the importance of environmental stewardship.", transcription: "Miduun subuka nuka baryo, kan diwata duun tu wuhig nu si Tala, mig bantuy tukan wuhig duw mig bugoy kandin to panalangin diya to mgo utow nug himo to marujow, tu miduun ug pang hinlo diya to wuhig duw ug tabang kan duma, si Tala iyan ug bugoy to panalangin. Sungo iduw, si Marco, suboka ka ligsok nu mag uuma, naka kita kandin tu maligsum siya to wuhig duw naningkamot kandin tug pang hinlo. Pagka tapos din tukan trabaho din, Naka kita kandin tu masiluw likat diya to wuhig, duw si Tala mig ileng, \" nakita ko kan karujow nu, Marco. Diwata sie likat kanay\" Si Tala mig bugoy to panalangin nu ug kahaw as kan kinabuhi ni Marco duw kan pamilya din. Kan baryo naamo nu kan panalangin ugka bugoy daun to ug himo kat marujow duw ug mapasalamaton kuw to guyangan.", translation: "In a village, the goddess of the river, Tala, watches over the water and gives grace to people who do bad things. If someone cleans the stream or helps others, Tala will give grace. One day, Marco, a farmer boy, saw garbage in the stream and tried to clean it. After his work, he saw a light from the water, and Tala said, \"I see your goodness, Marco. Accept it from me\" Tala gives grace that enriches the life of Marco and his family. The village learned that grace will only be given if you do good and give thanks to nature.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "FOLKTALE", themes: '["COURTSHIP_AND_MARRIAGE","NATURE_AND_ENVIRONMENT"]', culturalElements: '["2nd POV","Man VS Nature","Conflict and Resolution","River Goddess","Love & Relationships"]' },
  { title: "Yumad diya tu bubungan (The Mountain Native)", manoboTitle: "Yumad diya tu bubungan", englishTitle: "The Mountain Native", type: "ORAL_LITERATURE", content: "Martys encounters a tiger that teaches him about respecting nature and the interconnectedness of all living beings.", transcription: "Si Marty's, suboka nuka ligsok nu yumad, mig suroy kandin diya tu bubungan duw naka kita kandin tu suboka nuka tigre nu mig hubong diya to kabagnutan. Pig bagajan kandin to pamimangno tukan tiger \" ligsok, sie guyangan kinahangyan nu ug respetohon ta duw ug atimanon ta\" Namaan un si Marty's nu Kuna tibo tiger, maduut, miduun duma nu iyan pad ug bugoy ikuw tu karajawan kanit kalibutan", translation: "Martys, a native boy, was exploring the mountain and saw a tiger hiding in a grass. The tiger gave him advice \"Child, nature must be respected and taken care of.\" Martys learns that not all Tigers are evil, some of them can bring beauty to the world.", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "FOLKTALE", themes: '["COURTSHIP_AND_MARRIAGE","NATURE_AND_ENVIRONMENT","MORAL_LESSONS","HEROIC_DEEDS"]', culturalElements: '["2nd POV","Courage and Resilience","Animal Wisdom","Mountain Setting","Love & Relationships"]' },
  { title: "Tagbanwa tu Batasan (The Fairy of Misfortune)", manoboTitle: "Tagbanwa tu Batasan", englishTitle: "The Fairy of Misfortune", type: "ORAL_LITERATURE", content: "Mang Juan helps a child taken by a mischievous fairy, highlighting themes of bravery and compassion in the face of supernatural forces.", transcription: "Su kadukiliman, si mang Juan mig panuw pailing diya tu adgawan tapos din mig trabaho diyat uma. Nakita din kan maintok nu bata nu mig tyaho Dani to suboka Nuka karaan nu beto. \"Hintawa ka?\"pangusip ni mang Juan. \"Pig pudot at tagbanwa\" tabak tu ligsok, \"gusto ad ug uli Natingaya si mang Juan duw nahidok, Piro naka hunahuna kandin nug tabang. \" Ani ka naan likat?\" Kan ligsok mig hindo diyat batasan, \" diya a likat, pero Kuna a Dan tinuud nu anak.\" Si mang Juan nataga nu miduun tagbanwa diyat batadan nu mig pudot to ligsok. \" Miduun ka diya to pamilya ni nay Marta?\" \"Huo,\" kan ligsok mig iling. \"Pero kan yawa ko miduun mig hubong duun to maaslag nu kado diyat batadan.\" Si mang Juan mig dinali nug andiya to dapit nu pig iling tukan ligsok nu nakita din kan bata duw tinuud ba. Mig hubong diya to kado. Pig tiang din kan ligsok duw pig uli din diya to pamilya ni nay Marta.", translation: "One night, Mang Juan was walking to the river after working in the field. He found a small child crying near an old boat. \"Who are you?\" Mang Juan asked. \"The fairy took me,\" answered the boy, \"I want to go home.\" Mang Juan was surprised and scared, but decided to help. \"Where are you from?\" The boy pointed to the cornfield, \"I'm from here, but I'm not their real son.\" Mang Juan knows that the fairy in the orchard takes children. \"Are you in Aling Marta's family?\" \"Yes,\" the boy said. \"But my body is hidden in a big tree in the field.\" Mang Juan hurried and went to the place the boy said and found the boy who was real, hiding in the tree. He carried the child and returned it to Aling Marta's family", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "FOLKTALE", themes: '["HEROIC_DEEDS","MORAL_LESSONS","SUPERNATURAL_BEINGS"]', culturalElements: '["2nd POV","Man VS Nature","Conflict and Resolution","Stream Fairy","Diwata","Courage & Resilience"]' },
  // ── RIDDLES ───────────────────────────────────────────────────────────────
  { title: "Batong (Beans)", manoboTitle: "Batong", englishTitle: "Beans", type: "ORAL_LITERATURE", content: "The riddle uses visual comparisons of a bean plant's growth stages. The young sprout resembles a butterfly, while the mature plant resembles a worm.", transcription: "Tu maintok pad angud to kaba-kaba pag aslag angud unto bitok", translation: "When it's small, it looks like a butterfly- when it's big, it looks like a worm. Answer: Batong (Beans)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["NATURE_AND_ENVIRONMENT","SOCIAL_CUSTOMS"]', culturalElements: '["3rd POV","Identity and Self-Discovery","Plant Growth","Manobo Riddle"]' },
  { title: "Gitanom na tabako (Planted Tobacco)", manoboTitle: "Gitanom na tabako", englishTitle: "Planted Tobacco", type: "ORAL_LITERATURE", content: "This describes the tobacco plant's life cycle. Young plants are carefully tended, and when mature, the leaves are hung to dry.", transcription: "Tu maintok pad pig aling pad, pag aslag un pig bitoy", translation: "When it was little it nurtured, when it is getting big one it was hanged. Answer: Gi tanum nga tabaco (Planted Tobacco)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["NATURE_AND_ENVIRONMENT","AGRICULTURAL_CYCLES"]', culturalElements: '["3rd POV","Plant Life Cycle","Agricultural Practice","Manobo Riddle"]' },
  { title: "Tubo (Sugar Cane)", manoboTitle: "Tubo", englishTitle: "Sugar Cane", type: "ORAL_LITERATURE", content: "The riddle refers to the segmented structure of sugar cane. The water within the segments is contained, even when cut.", transcription: "Wuhig to rembo rembo tampudon kunag ka jabo", translation: "Water in limbo limbo did not spill. Answer: Tubo (Sugar Cane)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["MORAL_LESSONS","NATURE_AND_ENVIRONMENT"]', culturalElements: '["3rd POV","Conflict and Resolution","Plant Symbolism","Manobo Riddle"]' },
  { title: "Lubi (Coconut)", manoboTitle: "Lubi", englishTitle: "Coconut", type: "ORAL_LITERATURE", content: "\"Wheel of Eba\" refers to the coconut husk. The riddle highlights the coconut's water-retaining ability.", transcription: "Atabay ni eba kunag ka yakasan", translation: "Wheel of Eba will no run out of water. Answer: Lubi (Coconut)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["COURTSHIP_AND_MARRIAGE","NATURE_AND_ENVIRONMENT"]', culturalElements: '["3rd POV","Love and Relationship","Nature Symbolism","Manobo Riddle"]' },
  { title: "Damgo (Dream)", manoboTitle: "Damgo", englishTitle: "Dream", type: "ORAL_LITERATURE", content: "A trick riddle; the only escape from a tiger chasing you in a forest is if it's a dream.", transcription: "diya to guyangan, pig yakag tu tiger, amonohon nu pag yagoy?", translation: "You are in the forest, a tiger is chasing you, how can you escape? Answer: Pag mata nag damgo ra ka (Just wake up you’re just dreaming)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["HEROIC_DEEDS","SUPERNATURAL_BEINGS"]', culturalElements: '["3rd POV","Courage and Resilience","Dream World","Manobo Riddle"]' },
  { title: "Anino (Shadow)", manoboTitle: "Anino", englishTitle: "Shadow", type: "ORAL_LITERATURE", content: "A shadow is intangible and cannot be harmed by a bullet.", transcription: "Inggad pusilon, buhi gihapon", translation: "Even if you shoot it, it will be still alive. Answer: Anino (Shadow)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["SOCIAL_CUSTOMS","NATURE_AND_ENVIRONMENT"]', culturalElements: '["3rd POV","Identity and Self-Discovery","Shadow Symbolism","Manobo Riddle"]' },
  { title: "Uling (Charcoal)", manoboTitle: "Uling", englishTitle: "Charcoal", type: "ORAL_LITERATURE", content: "This riddle uses color to represent stages of coal burning: white coal, red-hot coal, and black charcoal.", transcription: "Si marites maputi kan bana din maitom", translation: "Marite is white, her husband is red, her son is black. Answer: Uling (charcoal)", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["NATURE_AND_ENVIRONMENT","MORAL_LESSONS"]', culturalElements: '["3rd POV","Transformation","Fire and Coal","Manobo Riddle"]' },
  { title: "Kahayag (Light)", manoboTitle: "Kahayag", englishTitle: "Light", type: "ORAL_LITERATURE", content: "The riddle refers to light's ability to transcend boundaries and enter a space without using the door.", transcription: "Kunag Baja to pultahan, likat diyat gawas pero ug abot diyat suyod", translation: "You don't go through the door, you come from outside but you come inside. Answer: Light", source: "Catipay & Curato (2024)", yearCollected: 2023, communityLocation: "Trento", province: "Agusan del Sur", municipality: "Trento", genre: "RIDDLE", themes: '["NATURE_AND_ENVIRONMENT","MORAL_LESSONS"]', culturalElements: '["3rd POV","Light Symbolism","Transcendence","Manobo Riddle"]' },
  {
    title: "The Creation of the Stars",
    manoboTitle: "Kagnat ne mga Bituen",
    englishTitle: "The Creation of the Stars",
    type: "ORAL_LITERATURE",
    content: "System classified as Origin Myth based on lexical frequency of \"Father Sky\" and \"Birth\" within the introductory markers.",
    transcription: "d-anak te meogingon so mga bituen te amay\nhe langit. Su kagi te meembon, amey ne\nlangit ne og-ilaan ne kandin ne mga bata.\n\nNe so kani ne timpu, wadad pa bituen te\nlangit. Madalumon pa so kapa-an te tano. Ne\nmig-iling so amey ne langit, \"Og-paka-anak\nki te mga bituen.\"",
    translation: "The stars were born from the breath of the\nFather Sky. According to the elders, the Sky\nFather wanted to give light to his children.\n\nIn those ancient times, there were no stars in\nthe heavens. The surface of the earth was\nstill in deep darkness. Then Father Sky said,\n\"We shall give birth to the stars.\"",
    source: "ML-ADS-1992-04",
    yearCollected: 1992,
    communityLocation: "Langasian",
    province: "Agusan del Sur",
    municipality: "La Paz",
    barangay: "Langasian",
    genre: "MYTH",
    themes: '["COSMOGONY","ORIGINS"]',
    culturalElements: '["Stars","Cosmogony","Origins","Myth"]'
  }
]

async function main() {
  await prisma.classification.deleteMany()
  await prisma.literatureEntry.deleteMany()

  for (const entry of entries) {
    await prisma.literatureEntry.create({ data: entry })
    console.log('  ✓', entry.title)
  }

  console.log('\n✅ Seeded', entries.length, 'entries!')
  await prisma.$disconnect()
}

main().catch(e => { console.error(e); process.exit(1) })
