export { classifyEntry } from './engine'
export type { ClassificationResult, RuleDetail, MatchedTerm } from './engine'
export { genreRules, themeRules, locationRules } from './rules'
export type { ClassificationRule } from './rules'
export { computeAccuracyMetrics } from './metrics'
export type { AccuracyMetrics } from './metrics'
